### ISSUE TITLE
Cant we do something like a set here? would be good if u can explain why this was done.

### ISSUE THREAD

**Issue by yasirysr47** [akgupta1337/Shazzam-Clone#3]
https://github.com/akgupta1337/Shazzam-Clone/blame/75b18e81d8cfbfc10710b79d5227942ee405dbec/logic/Shazzam.py#L154

**Comment by akgupta1337** [comment]
So basically, In a song there can be some parts which are repeating, therefore they will have same hashes and time offets, therefore we drop them, the reason we did not used sets was because sets are not ordered, and we needed to store data in the correct order.
